Add platform-specific compilation for miniaudio sizes (#48)
* Add platform-specific compilation for miniaudio sizes

This fixes the windows build process from failing with: 

```

Run New-Item -ItemType Directory -Force -Path bin

    Directory: D:\a\sands\sands

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          10/28/2025  7:50 PM                bin
   Creating library C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.lib and object C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exp
Showing last frame. Use --error-trace for full trace.

In lib\raylib-cr\src\raylib-cr\audio.cr:7:6

 7 | {{ run "./miniaudio_fix/ma_sizes" }}
        ^--
Error: Error executing run (exit code: 1): ./miniaudio_fix/ma_sizes 


stderr:

    Unhandled exception: Missing hash key: "ma_data_converter" (KeyError)
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +20727 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +247187 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +247068 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +17444 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +111117 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +112515 in '??'
      from C:\Users\runneradmin\AppData\Local\crystal\cache\D-a-sands-sands-lib-raylib-cr-src-raylib-cr-miniaudio_fix-ma_sizes.cr\macro_run.exe +311548 in '??'
      from C:\Windows\System32\KERNEL32.DLL +190679 in 'BaseThreadInitThunk'
      from C:\Windows\SYSTEM32\ntdll.dll +574780 in 'RtlUserThreadStart'


```

* fixed scoping

* output